### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by sj911098** [googlesamples/android-RuntimePermissionsWear#1]
Please help! I can not get building done, below is the error message:
Information:Gradle tasks [:Application:generateDebugSources, :Application:mockableAndroidJar, :Application:prepareDebugUnitTestDependencies, :Application:generateDebugAndroidTestSources, :Shared:generateDebugSources, :Shared:mockableAndroidJar, :Shared:prepareDebugUnitTestDependencies, :Shared:generateDebugAndroidTestSources, :Wearable:generateDebugSources, :Wearable:mockableAndroidJar, :Wearable:prepareDebugUnitTestDependencies, :Wearable:generateDebugAndroidTestSources]
Error:Execution failed for task ':Wearable:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0) from [com.android.support:wear:26.0.0] AndroidManifest.xml:25:13-35
	is also present at [com.android.support:support-v13:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.
Information:BUILD FAILED
Information:Total time: 2 mins 28.396 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by hgulati6789** [comment]
Any luck?

**Comment by codingjeremy** [comment]
Sorry for delay. I fixed this in the internal version. Should have it pushed this upcoming week for you (targets 28 and includes new androidx libraries).

**Comment by codingjeremy** [comment]
This has been pushed/fixed and migrated to the new wear-os repo: [github.com/android/wear-os](https://github.com/android/wear-os). Please review code there. Thank you!
